# ml-service/app.py
# Flask ML service — loads trained XGBoost model and serves predictions
# Run with: python app.py  (runs on port 5001)
# NOTE: Suggestions are now generated by Groq in the Node.js controller
#       This service ONLY predicts emission level (Low/Medium/High)

import ast
import pickle
import numpy as np
import pandas as pd
import xgboost as xgb
from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# Load model and artifacts on startup 
print("Loading XGBoost model...")
model = xgb.XGBClassifier()
model.load_model("eco_model.json")

with open("model_artifacts.pkl", "rb") as f:
    artifacts = pickle.load(f)

encoders         = artifacts["encoders"]
scaler           = artifacts["scaler"]
feature_cols     = artifacts["feature_cols"]
categorical_cols = artifacts["categorical_cols"]
numerical_cols   = artifacts["numerical_cols"]
encoded_cat_cols = artifacts["encoded_cat_cols"]
q33              = artifacts["q33"]
q66              = artifacts["q66"]

EMISSION_LABELS = {0: "Low", 1: "Medium", 2: "High"}
print("Model loaded! Flask running on http://localhost:5001")


# Helper: parse list fields
def parse_list(val):
    if isinstance(val, list):
        return val
    try:
        return ast.literal_eval(val)
    except:
        return []


# Helper: preprocess user input
def preprocess(data: dict) -> pd.DataFrame:
    # Default Vehicle Type if missing
    if not data.get("Vehicle Type"):
        data["Vehicle Type"] = "none"

    # Count recycling and cooking items
    data["Recycling_count"] = len(parse_list(data.get("Recycling", [])))
    data["Cooking_count"]   = len(parse_list(data.get("Cooking_With", [])))

    # Encode categorical columns
    row = {}
    for col in categorical_cols:
        le  = encoders[col]
        val = str(data.get(col, ""))
        row[col + "_enc"] = int(le.transform([val])[0]) if val in le.classes_ else 0

    # Numerical columns
    for col in numerical_cols:
        row[col] = float(data.get(col, 0))

    # Build DataFrame in correct feature order
    df_in = pd.DataFrame([[row[c] for c in feature_cols]], columns=feature_cols)

    # Scale numerical columns
    df_in[numerical_cols] = scaler.transform(df_in[numerical_cols])

    return df_in


# Route: health check 
@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok", "message": "ML service is running"})


# Route: predict emission level 
@app.route("/predict", methods=["POST"])

def predict():
    """
    POST /predict
    Accepts user lifestyle + carbon log fields
    Returns emission_level and confidence ONLY
    (Groq in Node.js controller handles suggestion generation)
    """

    try:
        data = request.get_json()
        
        if not data:
            return jsonify({"success": False, "message": "No data provided"}), 400

        features       = preprocess(data)
        pred           = model.predict(features)[0]
        proba          = model.predict_proba(features)[0]
        emission_level = EMISSION_LABELS[int(pred)]
        confidence     = round(float(max(proba)) * 100, 1)

        print(f"Predicted: {emission_level} ({confidence}% confidence)")

        # Only return emission level — suggestions handled by Groq in Node.js
        return jsonify({
            "success":        True,
            "emission_level": emission_level,
            "confidence":     confidence,
        })

    except Exception as e:
        print(f"Prediction error: {e}")
        
        return jsonify({
            "success": False,
            "message": "Failed to predict emission level.",
            "error":   str(e),
        }), 500


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5001, debug=True)
